/**
 * GENERATED by scripts/sync-legal.py from www.pyaasdairy.com/terms and /privacy.
 * Do not edit by hand: change the website, then re-run the script, so the app
 * and the website can never say different things (founder call, 21 Sep).
 */
import type { DocSection } from '../components/DocScreen';

export type LegalDoc = { updated: string; intro: string[]; sections: DocSection[] };

export const TERMS: LegalDoc = {
  "updated": "3 August 2026 · v1.0",
  "intro": [
    "Welcome to Pyaas. Our promise is simple: Know Your Milk. We bring fresh Parag milk and dairy products to your doorstep, with the transparency to see where your milk came from and how it reached you. These Terms are written to be fair and clear, in the same honest spirit.",
    "These Terms & Conditions (“Terms”) govern your access to and use of the Pyaas mobile application, our website www.pyaasdairy.com, and all related products, features, and services (together, the “Platform”), operated by PYAAS DAIRY PRIVATE LIMITED (“Pyaas”, “we”, “us”, or “our”). They constitute a legally binding agreement between you and Pyaas.",
    "Please read these Terms carefully. By downloading, accessing, registering on, or using the Platform, or by placing an order, you agree to be bound by these Terms and by our Privacy Policy, which is incorporated by reference. If you do not agree, please do not use the Platform. These Terms are an electronic record under the Information Technology Act, 2000 and do not require any physical or digital signature."
  ],
  "sections": [
    {
      "heading": "Welcome Litre Offer",
      "blocks": [
        {
          "kind": "para",
          "text": "We are running a Welcome Litre Offer for new milk subscribers in the PYAAS app: 1 litre of Parag Full Cream milk free. It is extra milk, not a discount, and the MRP does not change. In short:"
        },
        {
          "kind": "bullets",
          "items": [
            "First pack free. Start a subscription in the app; your first 500 ml pack arrives free on your first morning.",
            "Second pack free. Add ₹500 or more to your wallet in a single recharge within 7 days, and a second 500 ml pack is delivered free.",
            "No minimum period. Pause, change or cancel in the app at any time. One offer per mobile number and per delivery address.",
            "Full offer terms, including eligibility, the wallet and how the free packs work: Welcome Litre Offer: full terms."
          ]
        }
      ]
    },
    {
      "heading": "1. About us and these Terms",
      "blocks": [
        {
          "kind": "para",
          "text": "The Platform is owned and operated by PYAAS DAIRY PRIVATE LIMITED. During its launch pilot, Pyaas offers doorstep delivery of Parag milk and dairy products in association with the Pradeshik Cooperative Dairy Federation (PCDF) / Lucknow Milk Union. “Parag” is a brand of PCDF; Pyaas operates the digital ordering and last-mile delivery service."
        },
        {
          "kind": "para",
          "text": "Legal entity: Pyaas Dairy Private Limited"
        },
        {
          "kind": "para",
          "text": "Also referred to as: “Pyaas”, “we”, “us”, “our”"
        },
        {
          "kind": "para",
          "text": "Corporate Identity No. (CIN): U46302UW2026PTC255483"
        },
        {
          "kind": "para",
          "text": "PAN: AARCP2552Q"
        },
        {
          "kind": "para",
          "text": "Registered office: A-107, Omicron-II, Greater Noida, Gautam Buddha Nagar, Uttar Pradesh 201310, India"
        },
        {
          "kind": "para",
          "text": "Website: www.pyaasdairy.com"
        },
        {
          "kind": "para",
          "text": "Customer support: support@pyaasdairy.com · +91 96672 60050"
        }
      ]
    },
    {
      "heading": "2. Definitions",
      "blocks": [
        {
          "kind": "para",
          "text": "“Platform” means the Pyaas app, website, and related services."
        },
        {
          "kind": "para",
          "text": "“User”, “you” means any person who accesses or uses the Platform, including customers and subscribers."
        },
        {
          "kind": "para",
          "text": "“Products” means the milk, dairy, and other goods made available for purchase through the Platform."
        },
        {
          "kind": "para",
          "text": "“Order” means a one-time or recurring request placed by you to purchase Products."
        },
        {
          "kind": "para",
          "text": "“Subscription” means a recurring schedule of deliveries you set up on the Platform."
        },
        {
          "kind": "para",
          "text": "“Wallet” means the prepaid balance maintained in your Pyaas account."
        },
        {
          "kind": "para",
          "text": "“Delivery Partner” means riders, logistics, and supply partners engaged to fulfil and deliver your Orders."
        }
      ]
    },
    {
      "heading": "3. Eligibility",
      "blocks": [
        {
          "kind": "para",
          "text": "You must be at least 18 years of age and competent to contract under the Indian Contract Act, 1872 to use the Platform and place Orders. By using the Platform, you represent and warrant that you meet these requirements and that the information you provide is true, current, and complete."
        },
        {
          "kind": "para",
          "text": "If you are using the Platform on behalf of a household or another person, you confirm that you are authorised to do so and to bind them to these Terms."
        }
      ]
    },
    {
      "heading": "4. Your account",
      "blocks": [
        {
          "kind": "para",
          "text": "To use certain features, you must create an account using a valid mobile number and the requested details. You are responsible for maintaining the confidentiality of your login credentials and for all activity that takes place under your account."
        },
        {
          "kind": "para",
          "text": "Keep your account details accurate and up to date, including your delivery address and contact number."
        },
        {
          "kind": "para",
          "text": "Notify us promptly at support@pyaasdairy.com if you suspect any unauthorised use of your account."
        },
        {
          "kind": "para",
          "text": "We may suspend, restrict, or terminate your account if you breach these Terms, provide false information, or misuse the Platform (see Section 20)."
        }
      ]
    },
    {
      "heading": "5. The service we provide",
      "blocks": [
        {
          "kind": "para",
          "text": "Pyaas enables you to browse Products, place one-time Orders and set up Subscriptions, and receive doorstep delivery of Parag milk and dairy Products within our serviceable areas. Product availability, delivery slots, and serviceable areas may vary and change from time to time, and are indicated on the Platform."
        },
        {
          "kind": "para",
          "text": "We make reasonable efforts to keep Product descriptions, images, and availability accurate, but we do not warrant that all information is error-free. Images are indicative. In case of any discrepancy, the details confirmed at the time of your Order and applicable packaging will prevail."
        }
      ]
    },
    {
      "heading": "6. Orders and subscriptions",
      "blocks": [
        {
          "kind": "para",
          "text": "Placing Orders. You may place a one-time Order or create a Subscription for regular deliveries. When you place an Order, you make an offer to purchase the selected Products at the price and quantity shown. Your Order is confirmed when we accept it on the Platform."
        },
        {
          "kind": "para",
          "text": "Cut-off times. Orders, modifications, pauses, and cancellations for a given delivery must be made before the applicable cut-off time shown on the Platform (typically the night before an early-morning delivery). Requests made after the cut-off will apply from the next eligible delivery."
        },
        {
          "kind": "para",
          "text": "Managing Subscriptions. You can modify quantities, change Products, pause or resume, set vacation dates, or cancel your Subscription from the Platform, subject to the cut-off times."
        },
        {
          "kind": "para",
          "text": "You are responsible for ensuring sufficient Wallet balance or a valid payment method for scheduled deliveries."
        },
        {
          "kind": "para",
          "text": "We may, at our discretion, decline or limit Orders that appear abnormal, fraudulent, or in breach of these Terms."
        }
      ]
    },
    {
      "heading": "7. Delivery",
      "blocks": [
        {
          "kind": "para",
          "text": "Delivery location and access. You must provide a complete, accurate delivery address and any access or security instructions. Please ensure the Products can be received or safely left at your doorstep during the selected slot."
        },
        {
          "kind": "para",
          "text": "Delivery slots. We aim to deliver within the selected slot (for example, before 8:00 a.m.), but delivery times are estimates and may vary due to operational, weather, traffic, or other factors."
        },
        {
          "kind": "para",
          "text": "Receipt and risk. Risk and title in the Products pass to you upon delivery to your address or nominated delivery point. Where you instruct us to leave Products at your doorstep unattended, you accept the risk of loss or damage after delivery."
        },
        {
          "kind": "para",
          "text": "Failed delivery. If we are unable to deliver because the address is inaccessible, incorrect, or no one is available to receive a Product that requires hand-over, the delivery may be treated as completed and no refund may be due, except as required by law or our policies."
        },
        {
          "kind": "para",
          "text": "Non-availability. If a Product becomes unavailable, we may offer a suitable substitute or credit your Wallet for the undelivered item."
        }
      ]
    },
    {
      "heading": "8. Pricing, charges, and taxes",
      "blocks": [
        {
          "kind": "para",
          "text": "Prices for Products are shown on the Platform and are inclusive of applicable taxes unless stated otherwise. Delivery charges, convenience fees, or minimum-order requirements, if any, will be displayed before you confirm your Order."
        },
        {
          "kind": "para",
          "text": "We may change prices, fees, and charges from time to time. Any change will apply to Orders and Subscription deliveries scheduled after the change takes effect. It is your responsibility to review the applicable price before each delivery."
        }
      ]
    },
    {
      "heading": "9. Payments and Wallet",
      "blocks": [
        {
          "kind": "para",
          "text": "Payment methods. You can pay through the methods offered on the Platform, such as UPI, cards, net banking, or the Pyaas Wallet. Payments are processed by third-party payment partners; we do not store your full payment credentials."
        },
        {
          "kind": "para",
          "text": "Wallet / prepaid balance. You may add money to your Wallet to pay for deliveries. Wallet balances represent prepaid amounts for Products and are not a deposit, do not earn interest, and are non-transferable."
        },
        {
          "kind": "para",
          "text": "Auto-deduction for Subscriptions. For Subscriptions, applicable amounts may be deducted from your Wallet or chosen payment method for each scheduled delivery."
        },
        {
          "kind": "para",
          "text": "Failed or disputed payments. We may pause deliveries if a payment fails or your Wallet balance is insufficient. For payment disputes, please contact support@pyaasdairy.com."
        }
      ]
    },
    {
      "heading": "10. Offers, promotions, and referrals",
      "blocks": [
        {
          "kind": "para",
          "text": "We may run promotions, discounts, trial offers, referral rewards, and loyalty benefits from time to time. Each is subject to its own specific terms, eligibility, and validity period, which will be indicated on the Platform."
        },
        {
          "kind": "para",
          "text": "Launch and trial offers (for example, a free-milk trial for new users) are available to eligible new users only, are limited to one per household unless stated otherwise, and are non-transferable and not redeemable for cash. We may modify or withdraw any offer at any time without prior notice, except where the offer has already been validly availed. We reserve the right to withhold or reverse benefits obtained through misuse, fraud, or abuse."
        }
      ]
    },
    {
      "heading": "11. Cancellations, replacements, and refunds",
      "blocks": [
        {
          "kind": "para",
          "text": "Because milk and dairy are perishable and hygiene-sensitive, our returns and refunds approach is designed around food safety:"
        },
        {
          "kind": "bullets",
          "items": [
            "Before cut-off. You may cancel or modify an upcoming delivery free of charge before the applicable cut-off time; any amount paid will be credited to your Wallet or refunded.",
            "After cut-off. Once an Order has passed the cut-off or is out for delivery, it generally cannot be cancelled.",
            "Quality issues. If a Product is damaged, leaking, spoiled, incorrect, or short in quantity, please report it via the Platform or to support@pyaasdairy.com within the timeframe indicated on the Platform (typically the same day of delivery), with details and, where possible, a photograph. On verification, we will replace the Product or credit/refund the amount.",
            "Refunds. Approved refunds are ordinarily credited to your Wallet, or to your original payment method where required, within the timelines of the relevant payment provider.",
            "Subscription cancellation. You may cancel a Subscription at any time from the Platform; any unused prepaid Wallet balance may be refunded in accordance with applicable law, after deducting amounts due for delivered Products and any non-refundable promotional credits."
          ]
        }
      ]
    },
    {
      "heading": "12. Product quality, food safety, and Know Your Milk",
      "blocks": [
        {
          "kind": "para",
          "text": "We are committed to quality and transparency. Products are sourced, handled, and delivered in compliance with the Food Safety and Standards Act, 2006 (FSSAI) and applicable food-safety laws. Nutritional and product information appears on the packaging and, where available, on the Platform."
        },
        {
          "kind": "para",
          "text": "Our “Know Your Milk” feature lets you scan a pack to view traceability information about the Product. This information is provided in good faith for transparency; the authoritative details remain those printed on the pack, including the “best before / use by” date and storage instructions. Please refrigerate and consume Products as directed on the packaging."
        }
      ]
    },
    {
      "heading": "13. Your responsibilities and acceptable use",
      "blocks": [
        {
          "kind": "para",
          "text": "You agree to use the Platform lawfully and in good faith. You must not:"
        },
        {
          "kind": "bullets",
          "items": [
            "Provide false, misleading, or fraudulent information, or impersonate any person.",
            "Use the Platform for any unlawful, fraudulent, or abusive purpose, or in breach of any applicable law.",
            "Interfere with, disrupt, or attempt to gain unauthorised access to the Platform, its systems, or other users’ accounts.",
            "Introduce viruses, malware, or harmful code, or use bots, scrapers, or automated means without our permission.",
            "Misuse offers, referrals, or promotions, or create multiple accounts to obtain benefits you are not entitled to.",
            "Infringe our or any third party’s intellectual property or other rights, or post unlawful, offensive, or objectionable content.",
            "Resell or commercially exploit the Products or the Platform without our written consent."
          ]
        }
      ]
    },
    {
      "heading": "14. Communications",
      "blocks": [
        {
          "kind": "para",
          "text": "By registering, you agree that we may contact you through SMS, email, WhatsApp, push notifications, and calls for transactional and service purposes relating to your Orders, deliveries, payments, and account. Marketing communications are sent only where you have consented and may be opted out of at any time, as described in our Privacy Policy. You consent to receive such communications notwithstanding any registration under the Do-Not-Disturb (DND) registry, to the extent permitted by law."
        }
      ]
    },
    {
      "heading": "15. Intellectual property",
      "blocks": [
        {
          "kind": "para",
          "text": "The Platform and all associated content, including the Pyaas name, logo, “Know Your Milk” branding, text, graphics, software, and design, are owned by or licensed to Pyaas and are protected by intellectual property laws. You are granted a limited, non-exclusive, non-transferable, revocable licence to use the Platform for personal, non-commercial purposes in accordance with these Terms."
        },
        {
          "kind": "para",
          "text": "The “Parag” brand, marks, and artwork are the property of PCDF / the Lucknow Milk Union and are used in connection with the Products under the applicable arrangement. Nothing on the Platform grants you any right to use the Pyaas or Parag marks without prior written permission."
        }
      ]
    },
    {
      "heading": "16. Third-party services and links",
      "blocks": [
        {
          "kind": "para",
          "text": "The Platform may integrate with or link to third-party services (such as payment gateways and maps). We are not responsible for the content, policies, or practices of third parties. Your use of those services is governed by their own terms and privacy policies."
        }
      ]
    },
    {
      "heading": "17. Disclaimers",
      "blocks": [
        {
          "kind": "para",
          "text": "The Platform and the Products are provided on an “as is” and “as available” basis. To the maximum extent permitted by law, we disclaim all warranties not expressly stated in these Terms, including implied warranties of merchantability and fitness for a particular purpose. We do not warrant that the Platform will be uninterrupted, error-free, or secure, or that deliveries will always occur within estimated times. Nothing in these Terms limits any rights you have as a consumer under the Consumer Protection Act, 2019 or other applicable law that cannot be excluded."
        },
        {
          "kind": "para",
          "text": "For more detail on the limits of the information, images, and estimates we provide, please read our full Disclaimer, which forms part of these Terms."
        }
      ]
    },
    {
      "heading": "18. Limitation of liability",
      "blocks": [
        {
          "kind": "para",
          "text": "To the maximum extent permitted by law, Pyaas, its directors, employees, and partners shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or for any loss of profits, data, or goodwill, arising out of or in connection with your use of the Platform or the Products."
        },
        {
          "kind": "para",
          "text": "Our total aggregate liability to you for any claim arising out of or relating to an Order or these Terms shall not exceed the amount paid by you for the specific Product or Order giving rise to the claim. These limitations do not apply to liability that cannot be excluded or limited under applicable law."
        }
      ]
    },
    {
      "heading": "19. Indemnity",
      "blocks": [
        {
          "kind": "para",
          "text": "You agree to indemnify and hold harmless Pyaas and its directors, employees, and partners from and against any claims, losses, liabilities, damages, costs, and expenses (including reasonable legal fees) arising out of or in connection with your breach of these Terms, your misuse of the Platform, or your violation of any law or third-party right."
        }
      ]
    },
    {
      "heading": "20. Suspension and termination",
      "blocks": [
        {
          "kind": "para",
          "text": "You may stop using the Platform and close your account at any time. We may suspend or terminate your access to the Platform or any Subscription, with or without notice, if you breach these Terms, if we suspect fraud or misuse, or if required to comply with law or for operational reasons."
        },
        {
          "kind": "para",
          "text": "On termination, your right to use the Platform ceases. Any accrued rights and obligations, and provisions that by their nature should survive (including Sections 15, 17, 18, 19, and 22), will survive termination. Any refundable Wallet balance will be handled in accordance with Section 11 and applicable law."
        }
      ]
    },
    {
      "heading": "21. Force majeure",
      "blocks": [
        {
          "kind": "para",
          "text": "We shall not be liable for any failure or delay in performance caused by events beyond our reasonable control, including acts of God, natural disasters, epidemics or pandemics, strikes, supply or cold-chain disruptions, failures of Delivery Partners or utilities, network or payment-system outages, government actions, or civil disturbances."
        }
      ]
    },
    {
      "heading": "22. Governing law and dispute resolution",
      "blocks": [
        {
          "kind": "para",
          "text": "These Terms are governed by and construed in accordance with the laws of India. Subject to applicable law, the courts at Gautam Buddha Nagar (Greater Noida), Uttar Pradesh shall have exclusive jurisdiction over any dispute arising out of or in connection with these Terms."
        },
        {
          "kind": "para",
          "text": "Before initiating any formal proceedings, we encourage you to contact us so we can try to resolve the matter amicably. Any grievance may first be raised with our Grievance Officer (Section 23)."
        }
      ]
    },
    {
      "heading": "23. Grievance redressal and contact",
      "blocks": [
        {
          "kind": "para",
          "text": "In accordance with the Information Technology Act, 2000, the Consumer Protection Act, 2019, and the rules made under them, our Grievance Officer / customer-support contact details are:"
        },
        {
          "kind": "para",
          "text": "Grievance Officer: Pyaas Dairy Private Limited"
        },
        {
          "kind": "para",
          "text": "Entity: Pyaas Dairy Private Limited"
        },
        {
          "kind": "para",
          "text": "Address: A-107, Omicron-II, Greater Noida, Gautam Buddha Nagar, Uttar Pradesh 201310, India"
        },
        {
          "kind": "para",
          "text": "Email: support@pyaasdairy.com"
        },
        {
          "kind": "para",
          "text": "Phone: +91 96672 60050"
        },
        {
          "kind": "para",
          "text": "Hours: Monday to Saturday, 9:00 a.m. to 6:00 p.m., and Sunday, 8:00 a.m. to 1:00 p.m. IST"
        },
        {
          "kind": "para",
          "text": "Safety line: Milk quality or safety concern? Call 96672 60050 at any time."
        }
      ]
    },
    {
      "heading": "24. Changes to these Terms",
      "blocks": [
        {
          "kind": "para",
          "text": "We may update these Terms from time to time to reflect changes in our services, technology, or legal requirements. Where changes are material, we will notify you through the Platform or by other appropriate means. The “Last updated” date shows the latest revision. Your continued use of the Platform after an update constitutes acceptance of the revised Terms."
        }
      ]
    },
    {
      "heading": "25. Miscellaneous",
      "blocks": [
        {
          "kind": "para",
          "text": "Entire agreement. These Terms, together with the Privacy Policy and any offer-specific terms, constitute the entire agreement between you and Pyaas regarding the Platform."
        },
        {
          "kind": "para",
          "text": "Severability. If any provision is held invalid or unenforceable, the remaining provisions will continue in full force and effect."
        },
        {
          "kind": "para",
          "text": "Waiver. Our failure to enforce any right or provision is not a waiver of that right or provision."
        },
        {
          "kind": "para",
          "text": "Assignment. You may not assign these Terms without our consent. We may assign our rights and obligations to an affiliate or successor."
        },
        {
          "kind": "para",
          "text": "Language. These Terms are drafted in English, which shall prevail over any translation."
        }
      ]
    }
  ]
};

export const PRIVACY: LegalDoc = {
  "updated": "3 August 2026 · v1.0",
  "intro": [
    "At Pyaas, our promise is simple: Know Your Milk. You should always be able to see where your milk came from, who produced it, how it was tested, and how it reached your home. We believe you deserve that same clarity about your personal information: what we collect, why we collect it, who we share it with, and how you stay in control.",
    "This Privacy Policy (“Policy”) explains how PYAAS DAIRY PRIVATE LIMITED collects, uses, stores, shares, and protects your personal data when you access or use the Pyaas mobile application, our website www.pyaasdairy.com, and any related products, features, and services (together, the “Platform”). It is designed to comply with the Digital Personal Data Protection Act, 2023 (“DPDP Act”), the Information Technology Act, 2000, and the rules made under them, including the Reasonable Security Practices and Sensitive Personal Data or Information Rules, 2011 (“SPDI Rules”).",
    "Please read this Policy carefully. By creating an account, placing an order, or otherwise using the Platform, you confirm that you have read, understood, and agree to this Policy, together with our Terms & Conditions. If you do not agree, please do not use the Platform."
  ],
  "sections": [
    {
      "heading": "1. Our privacy principles",
      "blocks": [
        {
          "kind": "para",
          "text": "This Policy reflects the way we think about your data:"
        },
        {
          "kind": "bullets",
          "items": [
            "Transparency you can scan. Plain words, no hype. We tell you what we do with your data.",
            "Collect only what we need. We practise data minimisation and ask only for what is required to serve you.",
            "You stay in control. You can access, correct, or delete your data and withdraw consent at any time.",
            "Consumer-first and farmer-first. Your data is used to serve you better, never to exploit you.",
            "Security by default. We protect your information with reasonable technical and organisational safeguards.",
            "We never sell your personal data. Full stop."
          ]
        }
      ]
    },
    {
      "heading": "2. Who we are (Data Fiduciary)",
      "blocks": [
        {
          "kind": "para",
          "text": "The Platform is owned and operated by PYAAS DAIRY PRIVATE LIMITED. For the purposes of the DPDP Act, Pyaas is the “Data Fiduciary” that determines the purposes and means of processing your personal data. You are the “Data Principal”."
        },
        {
          "kind": "para",
          "text": "Legal entity: Pyaas Dairy Private Limited"
        },
        {
          "kind": "para",
          "text": "Also referred to as: “Pyaas”, “we”, “us”, “our”"
        },
        {
          "kind": "para",
          "text": "Corporate Identity No. (CIN): U46302UW2026PTC255483"
        },
        {
          "kind": "para",
          "text": "PAN: AARCP2552Q"
        },
        {
          "kind": "para",
          "text": "Registered office: A-107, Omicron-II, Greater Noida, Gautam Buddha Nagar, Uttar Pradesh 201310, India"
        },
        {
          "kind": "para",
          "text": "Website: www.pyaasdairy.com"
        },
        {
          "kind": "para",
          "text": "Contact email support@pyaasdairy.com"
        },
        {
          "kind": "para",
          "text": "Grievance Officer: Grievance Officer, Pyaas Dairy Private Limited · support@pyaasdairy.com"
        },
        {
          "kind": "para",
          "text": "During its launch pilot, Pyaas offers doorstep delivery of Parag milk and dairy products in association with the Pradeshik Cooperative Dairy Federation (PCDF) / Lucknow Milk Union. Parag is a brand of PCDF; Pyaas operates the digital ordering and delivery service."
        }
      ]
    },
    {
      "heading": "3. Scope of this Policy",
      "blocks": [
        {
          "kind": "para",
          "text": "This Policy applies to all users of the Platform, including customers, subscribers, delivery recipients, and website visitors, and to the personal data we process about them."
        },
        {
          "kind": "para",
          "text": "This Policy does not apply to third-party websites, applications, or services that we do not own or control, even if they are linked from or integrated with the Platform. Your use of those services is governed by their own privacy policies."
        }
      ]
    },
    {
      "heading": "4. Definitions",
      "blocks": [
        {
          "kind": "para",
          "text": "“Personal Data” means any data about an individual who is identifiable by or in relation to such data."
        },
        {
          "kind": "para",
          "text": "“Sensitive Personal Data or Information (SPDI)” has the meaning given under the SPDI Rules and includes, for example, financial information such as payment instrument details."
        },
        {
          "kind": "para",
          "text": "“Processing” means any operation performed on personal data, such as collection, storage, use, sharing, or erasure."
        },
        {
          "kind": "para",
          "text": "“Data Principal” means you, the individual to whom the personal data relates."
        },
        {
          "kind": "para",
          "text": "“Data Fiduciary” means Pyaas, which determines the purpose and means of processing."
        },
        {
          "kind": "para",
          "text": "“Delivery Partner” means riders, logistics providers, and supply partners engaged to fulfil and deliver your orders."
        },
        {
          "kind": "para",
          "text": "“Platform” means the Pyaas app, website, and related services."
        }
      ]
    },
    {
      "heading": "5. Information we collect",
      "blocks": [
        {
          "kind": "para",
          "text": "Information you provide to us."
        },
        {
          "kind": "para",
          "text": "Account & identity: name, mobile number, email address, password, and profile details."
        },
        {
          "kind": "para",
          "text": "Delivery information: delivery address(es), flat/house number, tower, society or apartment name, landmark, PIN code, gate/security instructions, delivery preferences, and the recipient’s name."
        },
        {
          "kind": "para",
          "text": "Subscription & order details: products selected, quantities, delivery slots, subscription schedules, vacation/pause settings, and order history."
        },
        {
          "kind": "para",
          "text": "Payment information: UPI ID, card details, wallet/credits, billing details, transaction records, and GST number (if you provide one). Full card numbers and payment credentials are processed by our payment gateway partners; we do not store your complete card details on our systems."
        },
        {
          "kind": "para",
          "text": "Communications & feedback: messages and call records with our support team, ratings, reviews, survey responses, complaints, and any other information you choose to share."
        },
        {
          "kind": "para",
          "text": "Referrals: contact details you provide to refer a friend. You must have their consent before sharing their information with us."
        },
        {
          "kind": "para",
          "text": "Information we collect automatically."
        },
        {
          "kind": "para",
          "text": "Device & technical data: device model, operating system, unique device identifiers, IP address, mobile network, app version, language settings, and diagnostic/crash logs."
        },
        {
          "kind": "para",
          "text": "Usage & interaction data: screens and pages viewed, features used, taps, time spent, search queries, and referring links."
        },
        {
          "kind": "para",
          "text": "Location data: precise or approximate location (with your permission) to determine serviceability, map your delivery address, and enable rider navigation."
        },
        {
          "kind": "para",
          "text": "Cookies & similar technologies: as described in Section 8."
        },
        {
          "kind": "para",
          "text": "Know-Your-Milk scan activity: when you scan the QR code on a pack, we record the scan event, the pack/batch identifier, and the time, so we can show you the product’s traceability record and improve quality."
        },
        {
          "kind": "para",
          "text": "Information from third parties. We may receive information about you from payment gateways and banks (transaction status), Delivery Partners, analytics and attribution providers, third-party sign-in services (if you choose to use them), PCDF / Lucknow Milk Union and dairy supply partners (for order fulfilment and product/traceability data), and publicly available sources."
        },
        {
          "kind": "para",
          "text": "Sensitive personal data. We do not ordinarily seek sensitive personal data. Where we handle financial information as part of a payment, we treat it as SPDI and apply reasonable security practices. We do not require health, biometric, genetic, or similar data to provide the service."
        }
      ]
    },
    {
      "heading": "6. How we use your information",
      "blocks": [
        {
          "kind": "para",
          "text": "We use your personal data for the following purposes:"
        },
        {
          "kind": "bullets",
          "items": [
            "To create, manage, and secure your account and to authenticate you.",
            "To process, fulfil, and deliver your orders and subscriptions to your doorstep.",
            "To optimise delivery routes and slots and to enable rider navigation.",
            "To process payments, generate invoices, issue refunds, and manage your wallet and credits.",
            "To provide the Know-Your-Milk traceability experience, quality records, and QR verification.",
            "To provide customer support and to receive and resolve your queries and complaints.",
            "To send you transactional and service communications relating to your orders, deliveries, payments, and subscriptions.",
            "To send you offers, promotions, newsletters, and personalised recommendations, where you have consented.",
            "To operate our loyalty, referral, and rewards programmes.",
            "To understand usage and to analyse, maintain, and improve the Platform, our products, and our service quality.",
            "To detect, prevent, and address fraud, abuse, security incidents, and technical issues.",
            "To comply with legal, regulatory, tax, and accounting obligations and to enforce our terms and policies.",
            "For any other purpose disclosed to you at the time of collection or with your consent."
          ]
        }
      ]
    },
    {
      "heading": "7. Grounds for processing",
      "blocks": [
        {
          "kind": "para",
          "text": "We process your personal data on the basis of your consent and, where permitted by the DPDP Act, for “certain legitimate uses”, for example, the purpose for which you have voluntarily provided your data, compliance with a legal obligation, and responding to an emergency involving a threat to life or safety."
        },
        {
          "kind": "para",
          "text": "You may withdraw your consent at any time (see Section 13). Withdrawal will not affect the lawfulness of processing carried out before withdrawal, and it may limit or prevent our ability to provide certain features or services."
        }
      ]
    },
    {
      "heading": "8. Cookies and tracking technologies",
      "blocks": [
        {
          "kind": "para",
          "text": "We and our service providers use cookies, software development kits (SDKs), pixels, device identifiers, and similar technologies to keep you signed in, remember your preferences, understand how the Platform is used, measure the performance of our communications and campaigns, and improve your experience."
        },
        {
          "kind": "para",
          "text": "These technologies fall into broad categories: strictly necessary (required for the Platform to function), functional (to remember your choices), analytics (to understand usage), and advertising (to measure and, where you consent, personalise marketing)."
        },
        {
          "kind": "para",
          "text": "You can manage cookies through your browser settings and control advertising identifiers and ad personalisation through your device settings. Disabling some cookies or identifiers may affect the functionality of the Platform."
        }
      ]
    },
    {
      "heading": "9. How we share and disclose your information",
      "blocks": [
        {
          "kind": "para",
          "text": "We do not sell your personal data. We share it only where necessary, and only with parties bound to protect it, including:"
        },
        {
          "kind": "bullets",
          "items": [
            "Delivery Partners and riders to fulfil and deliver your orders (for example, your name, address, phone number, delivery instructions, and order details).",
            "PCDF / Lucknow Milk Union and dairy supply and production partners for order fulfilment, product supply, quality assurance, and traceability, on a need-to-know basis.",
            "Payment processors, gateways, banks, and UPI providers to process your payments and refunds securely.",
            "Technology service providers cloud hosting and storage, communications (SMS, email, WhatsApp, push notifications), analytics, mapping, and customer-support providers, under confidentiality and data-protection obligations.",
            "Marketing and advertising partners to deliver and measure campaigns, where you have consented.",
            "Professional advisors and auditors such as lawyers, accountants, and insurers, where reasonably required.",
            "Legal and regulatory authorities where required by law, regulation, legal process, or enforceable governmental request, or to protect the rights, property, or safety of Pyaas, our users, or the public, and to prevent fraud.",
            "Group companies and affiliates for the purposes described in this Policy.",
            "In a business transfer in connection with a merger, acquisition, reorganisation, financing, or sale of assets, subject to this Policy.",
            "With your consent for any other disclosure.",
            "Data we share, stated plainly. Some data leaves our systems the moment you use the service, and we would rather say so than bury it. This is the same list our app store data-safety declaration must carry, so the two always agree.",
            "Your phone number is shared with our SMS provider every time we send a one-time password or a delivery notification. It is transferred and stored by them to deliver the message. Without this you cannot sign in.",
            "Your payment details are shared with our payment processor when you pay. Card and UPI credentials go directly to the processor and are handled under their PCI-DSS obligations. We never receive or store your full card number.",
            "Your name, address and phone are shared with delivery partners so an order can physically reach you.",
            "We do not sell your personal data, and we do not share it with data brokers or for anyone else’s independent advertising."
          ]
        }
      ]
    },
    {
      "heading": "10. Third-party links and services",
      "blocks": [
        {
          "kind": "para",
          "text": "The Platform may contain links to, or integrations with, third-party websites, applications, and services (for example, payment pages and social media). We are not responsible for the privacy practices or content of those third parties. We encourage you to review their privacy policies before providing them with your information."
        }
      ]
    },
    {
      "heading": "11. Data retention",
      "blocks": [
        {
          "kind": "para",
          "text": "We retain your personal data only for as long as necessary to fulfil the purposes described in this Policy, to provide the Platform to you, and to comply with our legal, tax, accounting, and regulatory obligations, resolve disputes, and enforce our agreements. The periods we work to are set out below."
        },
        {
          "kind": "para",
          "text": "Account and profile While your account is open, then deleted within 30 days of closure."
        },
        {
          "kind": "para",
          "text": "Orders, invoices and payment records Eight years, as required by the Companies Act, GST and income-tax rules."
        },
        {
          "kind": "para",
          "text": "Delivery addresses While your account is open, then deleted with the account."
        },
        {
          "kind": "para",
          "text": "Support and grievance correspondence Three years from the date the matter is closed."
        },
        {
          "kind": "para",
          "text": "Founding Family and marketing contacts Until you unsubscribe or ask us to delete them."
        },
        {
          "kind": "para",
          "text": "Reviews you publish Until you ask us to remove them."
        },
        {
          "kind": "para",
          "text": "Server and security logs One hundred and eighty days."
        },
        {
          "kind": "para",
          "text": "Backups Purged on the normal backup cycle, within 90 days of deletion."
        },
        {
          "kind": "para",
          "text": "When your personal data is no longer required, we will delete, anonymise, or de-identify it. Some data may persist for a limited period in secure backups before being overwritten."
        }
      ]
    },
    {
      "heading": "12. Data security",
      "blocks": [
        {
          "kind": "para",
          "text": "We implement reasonable security practices and procedures in line with the IT Act and the SPDI Rules, including encryption of data in transit, access controls, secure infrastructure, and appropriate organisational measures. Payment card data is handled by PCI-DSS-compliant payment partners; we do not store your full card details."
        },
        {
          "kind": "para",
          "text": "No method of transmission or storage is completely secure, and we cannot guarantee absolute security. You are responsible for keeping your login credentials confidential and for any activity under your account. If we become aware of a personal data breach, we will act in accordance with applicable law, including notifying the Data Protection Board of India and affected users where required."
        }
      ]
    },
    {
      "heading": "13. Your rights and choices",
      "blocks": [
        {
          "kind": "para",
          "text": "Subject to applicable law, you have the following rights in relation to your personal data:"
        },
        {
          "kind": "bullets",
          "items": [
            "Right to access to obtain a summary of the personal data we process about you and how we process it.",
            "Right to correction and completion to have inaccurate or incomplete data corrected, completed, or updated.",
            "Right to erasure to request deletion of your personal data, subject to legal and regulatory retention requirements.",
            "Right to withdraw consent to withdraw consent you have given, at any time, as easily as you gave it.",
            "Right of grievance redressal to have your grievances addressed by our Grievance Officer.",
            "Right to nominate to nominate another individual to exercise your rights in the event of your death or incapacity.",
            "Marketing choices to opt out of promotional communications at any time.",
            "Device permissions to manage location, notification, and other permissions through your device settings."
          ]
        }
      ]
    },
    {
      "heading": "14. How to exercise your rights and grievance redressal",
      "blocks": [
        {
          "kind": "para",
          "text": "To exercise any of your rights, contact us at support@pyaasdairy.com or reach our Grievance Officer using the details in Section 21. To delete your account and personal data, you can also use our dedicated account & data deletion page. We may need to verify your identity before acting on your request. We will respond within the timelines prescribed under applicable law."
        },
        {
          "kind": "para",
          "text": "If you are not satisfied with our response, you may escalate your grievance to the Data Protection Board of India in accordance with the DPDP Act."
        }
      ]
    },
    {
      "heading": "15. Children’s data",
      "blocks": [
        {
          "kind": "para",
          "text": "The Platform is intended for individuals who are 18 years of age or older. We do not knowingly collect the personal data of children (individuals under 18) without the verifiable consent of a parent or lawful guardian, as required under the DPDP Act. We do not undertake tracking, behavioural monitoring, or targeted advertising directed at children."
        },
        {
          "kind": "para",
          "text": "If you believe that a child has provided us with personal data without appropriate consent, please contact us and we will take steps to delete it."
        }
      ]
    },
    {
      "heading": "16. Marketing communications and preferences",
      "blocks": [
        {
          "kind": "para",
          "text": "Where you have consented, we may send you offers, updates, and promotional content by SMS, email, WhatsApp, push notification, or phone call. You can opt out at any time using the unsubscribe option in the message, your app notification settings, or by contacting us."
        },
        {
          "kind": "para",
          "text": "Please note that transactional and service messages, for example, order confirmations, delivery updates, and payment alerts, are not marketing communications and may still be sent to you while you use the Platform. We honour applicable Do-Not-Disturb (DND) and telecom regulatory requirements."
        }
      ]
    },
    {
      "heading": "17. Location data",
      "blocks": [
        {
          "kind": "para",
          "text": "With your permission, we collect precise or approximate location data to check whether we deliver in your area, to map your delivery address accurately, to enable rider navigation, and to improve delivery reliability. You can enable or disable location access at any time through your device settings, though doing so may affect certain delivery features."
        }
      ]
    },
    {
      "heading": "18. Data storage and cross-border transfers",
      "blocks": [
        {
          "kind": "para",
          "text": "Your personal data is generally stored and processed on servers located in India. Where we transfer or store data outside India (for example, with cloud or technology providers), we do so in accordance with the DPDP Act and other applicable law, and we apply appropriate safeguards to protect your data."
        }
      ]
    },
    {
      "heading": "19. Changes to this Policy",
      "blocks": [
        {
          "kind": "para",
          "text": "We may update this Policy from time to time to reflect changes in our practices, technology, legal requirements, or for other operational reasons. Where changes are material, we will notify you through the Platform or by other appropriate means. The “Last updated” date at the top of this Policy indicates when it was last revised. Your continued use of the Platform after an update constitutes your acceptance of the revised Policy."
        }
      ]
    },
    {
      "heading": "20. Governing law and jurisdiction",
      "blocks": [
        {
          "kind": "para",
          "text": "This Policy is governed by and construed in accordance with the laws of India. Subject to applicable law, the courts at Gautam Buddha Nagar (Greater Noida), Uttar Pradesh shall have exclusive jurisdiction over any dispute arising out of or in connection with this Policy."
        }
      ]
    },
    {
      "heading": "21. Grievance Officer and contact details",
      "blocks": [
        {
          "kind": "para",
          "text": "In accordance with the Information Technology Act, 2000 and the rules made under it, and the DPDP Act, the contact details of our Grievance Officer / data protection contact are:"
        },
        {
          "kind": "para",
          "text": "Grievance Officer: Pyaas Dairy Private Limited"
        },
        {
          "kind": "para",
          "text": "Entity: Pyaas Dairy Private Limited"
        },
        {
          "kind": "para",
          "text": "Address: A-107, Omicron-II, Greater Noida, Gautam Buddha Nagar, Uttar Pradesh 201310, India"
        },
        {
          "kind": "para",
          "text": "Email: support@pyaasdairy.com"
        },
        {
          "kind": "para",
          "text": "Hours: Monday to Saturday, 9:00 a.m. to 6:00 p.m., and Sunday, 8:00 a.m. to 1:00 p.m. IST"
        },
        {
          "kind": "para",
          "text": "Safety line: Milk quality or safety concern? Call 96672 60050 at any time."
        }
      ]
    },
    {
      "heading": "22. Consent and acknowledgement",
      "blocks": [
        {
          "kind": "para",
          "text": "By accessing or using the Platform, you acknowledge that you have read and understood this Privacy Policy and consent to the collection, use, storage, sharing, and processing of your personal data as described here. If you do not agree with this Policy, please do not use the Platform."
        }
      ]
    }
  ]
};
