import React from 'react';
import { DocScreen } from '../components/DocScreen';
import { TERMS } from '../constants/legal';

/**
 * TERMS AND CONDITIONS — exactly the text published at
 * www.pyaasdairy.com/terms (founder call, 21 Sep: "sync the app terms and the
 * website terms"). The app used to carry its own shortened rewrite, which had
 * already drifted from the website (a different CIN, missing sections). The
 * text now lives in constants/legal.ts, generated by scripts/sync-legal.py
 * from the website, so the two can only differ until the script is re-run.
 */
export default function Terms() {
  return (
    <DocScreen
      title="Terms and Conditions"
      updated={TERMS.updated}
      intro={TERMS.intro.join('\n\n')}
      sections={TERMS.sections}
    />
  );
}
