#!/usr/bin/env python3
"""
Sync the app's Terms and Privacy Policy with www.pyaasdairy.com.

The website is the published legal text. This script fetches /terms and
/privacy, keeps the document body (intro, the Welcome Litre Offer box, the
numbered sections), and writes constants/legal.ts, which app/terms.tsx and
app/privacy-policy.tsx render. Run it whenever the website text changes:

    python3 scripts/sync-legal.py

No wording is edited: lines are copied as published. Only layout is inferred
(section headings, "Label value" table rows, and bullet lists that follow a
line ending in a colon).
"""
import html, json, re, urllib.request

SITE = 'https://www.pyaasdairy.com'
TABLE_LABELS = [
    'Corporate Identity No. (CIN)', 'Also referred to as', 'Registered office', 'Customer support',
    'Grievance Officer', 'Legal entity', 'Safety line', 'Website', 'Address', 'Entity', 'Email',
    'Phone', 'Hours', 'PAN',
]

def fetch_lines(path):
    req = urllib.request.Request(SITE + path, headers={'User-Agent': 'PYAAS-app-legal-sync'})
    s = urllib.request.urlopen(req, timeout=60).read().decode('utf-8', 'ignore')
    s = re.sub(r'<(script|style|noscript|svg)[^>]*>.*?</\1>', ' ', s, flags=re.S | re.I)
    s = re.sub(r'<br\s*/?>', '\n', s)
    s = re.sub(r'</(p|div|h\d|li|section|tr|td)>', '\n', s, flags=re.I)
    t = html.unescape(re.sub(r'<[^>]+>', ' ', s))
    t = re.sub(r'[ \t ]+', ' ', t)
    return [l.strip() for l in t.split('\n') if l.strip()]

def tidy(line):
    # Inline links leave a space before punctuation ("Privacy Policy , which").
    return re.sub(r'\s+([,.;:])', r'\1', line).strip()

def table_row(line):
    for label in TABLE_LABELS:
        if line.startswith(label + ' '):
            return f'{label}: {line[len(label) + 1:]}'
    return None

def parse(lines, box_heading=None):
    start = next(i for i, l in enumerate(lines) if l.startswith('Effective '))
    meta = lines[start]
    end = next(i for i, l in enumerate(lines) if 'Back to home' in l and i > start)
    body = lines[start + 1:end]
    # Drop the "On this page" table of contents.
    out, skipping = [], False
    for l in body:
        if l.startswith('On this page'):
            skipping = True
            continue
        if skipping:
            if re.match(r'^\d+\. ', l):
                continue
            skipping = False
        out.append(l)
    intro, sections, cur = [], [], None
    for l in out:
        m = re.match(r'^(\d{2}) (.+)$', l)
        if m or (box_heading and l == box_heading and cur is None):
            heading = f'{int(m.group(1))}. {m.group(2)}' if m else box_heading
            cur = {'heading': heading, 'lines': []}
            sections.append(cur)
            continue
        (cur['lines'] if cur else intro).append(tidy(l))
    for s in sections:
        blocks, bullets = [], None
        for l in s.pop('lines'):
            row = table_row(l)
            if row:
                if bullets: blocks.append({'kind': 'bullets', 'items': bullets}); bullets = None
                blocks.append({'kind': 'para', 'text': row})
                continue
            if bullets is not None and not l.endswith(':'):
                bullets.append(l)
                continue
            if bullets: blocks.append({'kind': 'bullets', 'items': bullets}); bullets = None
            blocks.append({'kind': 'para', 'text': l})
            if l.endswith(':'):
                bullets = []
        if bullets: blocks.append({'kind': 'bullets', 'items': bullets})
        s['blocks'] = blocks
    m = re.search(r'Updated (.+?) Version (\S+)', meta)
    updated = f'{m.group(1)} · v{m.group(2)}' if m else meta
    return {'updated': updated, 'intro': intro, 'sections': sections}

terms = parse(fetch_lines('/terms'), box_heading='Welcome Litre Offer')
privacy = parse(fetch_lines('/privacy'))

header = '''/**
 * GENERATED by scripts/sync-legal.py from www.pyaasdairy.com/terms and /privacy.
 * Do not edit by hand: change the website, then re-run the script, so the app
 * and the website can never say different things (founder call, 21 Sep).
 */
import type { DocSection } from '../components/DocScreen';

export type LegalDoc = { updated: string; intro: string[]; sections: DocSection[] };

'''
with open('constants/legal.ts', 'w', encoding='utf-8') as f:
    f.write(header)
    f.write('export const TERMS: LegalDoc = ' + json.dumps(terms, ensure_ascii=False, indent=2) + ';\n\n')
    f.write('export const PRIVACY: LegalDoc = ' + json.dumps(privacy, ensure_ascii=False, indent=2) + ';\n')
print('terms', len(terms['sections']), 'sections · privacy', len(privacy['sections']), 'sections')
